# Generated by Django 4.2.7 on 2024-03-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0003_kruzok_student_kruzok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kruzok',
            options={'ordering': ['nazov'], 'verbose_name': 'Krúžok', 'verbose_name_plural': 'Krúžky'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Študent', 'verbose_name_plural': 'Študenti'},
        ),
        migrations.AlterModelOptions(
            name='trieda',
            options={'ordering': ['nazov'], 'verbose_name': 'Trieda', 'verbose_name_plural': 'Triedy'},
        ),
        migrations.AlterModelOptions(
            name='ucitel',
            options={'ordering': ['priezvisko'], 'verbose_name': 'Učitel', 'verbose_name_plural': 'Učitelia'},
        ),
    ]
