# Generated by Django 4.2.7 on 2024-04-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0004_alter_kruzok_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='obec',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='psc',
            field=models.CharField(default='null', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ulica',
            field=models.CharField(default='null', max_length=50),
            preserve_default=False,
        ),
    ]
