# Generated by Django 4.2.7 on 2024-04-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skola', '0005_student_obec_student_psc_student_ulica'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='datum_narodenia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rok_narodenia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='vek',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='datum_narodenia',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='obec',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='psc',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='rok_narodenia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ucitel',
            name='ulica',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
