# Generated by Django 5.0.1 on 2024-03-07 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pocet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bodiky',
            new_name='High_score',
        ),
    ]
